title: dtc innovation
tag_text: dtc innovation
description: Designing Technology for the Commons.
baseurl: ""

font-awesome-include: false

collections:
  projects:
    render: true
    resources:
      github: GitHub Project
      website: Website

company:
  siren: '823553557'
  siret: '82355355700013'
  vat: 'FR67823553557'
  since: 2016-09-16

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
