title: dtc innovation
tag_text: dtc innovation
description: Designing Technology for the Commons.
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:title
    resources:
      github: GitHub Project
      website: Website

company:
  siren: '823553557'
  siret: '82355355700013'
  vat: 'FR67823553557'
  since: 2016-09-16

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-seo-tag
