---
---

backend:
  name: github
  repo: dtc-innovation/dtc-innovation.github.io
  branch: master

media_folder: "images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "project"
    label: "Project"
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Name"
        name: "name"
        widget: "string"
        tagname: "h1"
      - label: "Short Description"
        name: "short_description"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Customer"
        name: "customer"
        widget: "select"
        options: ["", {% for d in site.data.customers %}{{ d[0] | jsonify }},{% endfor %}]
        required: false
      - label: "Labels"
        name: "labels"
        widget: "list"
        required: false
      - label: "Highlight Order"
        name: "highlights_order"
        widget: "number"
        required: false
      - label: "Current Stage"
        name: "current_stage"
        widget: "string"
        required: false
      - label: "Next Stage"
        name: "next_stage"
        widget: "string"
        required: false
      - label: "Resources"
        name: "resources"
        widget: "object"
        required: false
        fields:
          - label: "GitHub"
            name: "github"
            widget: "string"
            required: false
          - label: "Website"
            name: "website"
            widget: "string"
            required: false
